sudo: false
language: scala
jdk:
- oraclejdk8
- oraclejdk9
services:
- docker
cache:
  directories:
  - "$HOME/.ivy2/cache"
  - "$HOME/.sbt/launchers"
script:
- sbt test
before_cache:
- find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
